"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useGetUserGenerationStatsQuery, useGetAllGenerationsQuery } from "@/lib/feature/admin/adminApi";
import { Search, ChevronLeft, ChevronRight, Download, Image as ImageIcon } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";

// Component for the user's generation history inside the modal
function UserGenerationsModal({ userId, userName, isOpen, onClose }: { userId: string, userName: string, isOpen: boolean, onClose: () => void }) {
  const [page, setPage] = useState(1);
  const { data, isLoading } = useGetAllGenerationsQuery({ page, limit: 12, userId }, { skip: !isOpen || !userId });

  const handleDownload = async (imageUrl: string, title: string) => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${title || 'generated-image'}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error("Download failed", error);
      // Fallback: open in new tab
      window.open(imageUrl, '_blank');
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{userName}'s Generation History</DialogTitle>
          <DialogDescription>All images and metadata generated by this user.</DialogDescription>
        </DialogHeader>
        
        <div className="mt-4">
          {isLoading ? (
            <div className="flex justify-center items-center py-12">
              <span className="animate-pulse text-muted-foreground">Loading generations...</span>
            </div>
          ) : data?.generations?.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground border rounded-lg bg-muted/20">
              No generation history found for this user.
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                {data?.generations?.map((item: any) => (
                  <Card key={item._id} className="overflow-hidden flex flex-col">
                    <div className="aspect-square bg-muted relative group">
                      {item.imageUrl ? (
                        <img src={item.imageUrl} alt={item.title} className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105" />
                      ) : (
                        <div className="flex items-center justify-center w-full h-full text-muted-foreground">
                          <ImageIcon className="h-8 w-8 opacity-50" />
                        </div>
                      )}
                    </div>
                    <CardContent className="p-4 flex-1">
                      <h4 className="font-medium truncate" title={item.title || 'Untitled'}>{item.title || 'Untitled'}</h4>
                      <div className="flex justify-between items-center mt-2 text-xs text-muted-foreground">
                        <span className="bg-primary/10 text-primary px-2 py-0.5 rounded-full capitalize">{item.category}</span>
                        <span>{new Date(item.createdAt).toLocaleDateString()}</span>
                      </div>
                    </CardContent>
                    <CardFooter className="p-4 pt-0">
                      <Button 
                        variant="secondary" 
                        size="sm" 
                        className="w-full gap-2"
                        onClick={() => handleDownload(item.imageUrl, item.title)}
                        disabled={!item.imageUrl}
                      >
                        <Download className="h-4 w-4" /> Download
                      </Button>
                    </CardFooter>
                  </Card>
                ))}
              </div>
              
              {data?.pages > 1 && (
                <div className="flex items-center justify-between mt-6 pt-4 border-t">
                  <div className="text-sm text-muted-foreground">
                    Page {page} of {data.pages}
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1 || isLoading}>
                      Prev
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => setPage(p => Math.min(data.pages, p + 1))} disabled={page >= data?.pages || isLoading}>
                      Next
                    </Button>
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default function AdminImagesPage() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [selectedUser, setSelectedUser] = useState<{ id: string, name: string } | null>(null);
  
  const { data, isLoading } = useGetUserGenerationStatsQuery({ page, limit: 12, search });

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setPage(1);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">User Generations</h2>
          <p className="text-muted-foreground">View and download image generation stats per user.</p>
        </div>
        
        <form onSubmit={handleSearch} className="flex gap-2 w-full sm:w-auto">
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Search user name, email..."
              className="pl-8"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <Button type="submit" variant="secondary">Search</Button>
        </form>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <Card key={i} className="animate-pulse">
              <CardHeader className="flex flex-row items-center gap-4 pb-2">
                <div className="h-12 w-12 rounded-full bg-muted"></div>
                <div className="space-y-2 flex-1">
                  <div className="h-4 bg-muted rounded w-3/4"></div>
                  <div className="h-3 bg-muted rounded w-1/2"></div>
                </div>
              </CardHeader>
              <CardContent className="pb-2">
                <div className="h-16 bg-muted/50 rounded-lg flex items-center justify-center">
                  <div className="h-6 bg-muted rounded w-1/3"></div>
                </div>
              </CardContent>
              <CardFooter>
                <div className="h-10 bg-muted rounded w-full"></div>
              </CardFooter>
            </Card>
          ))}
        </div>
      ) : data?.stats?.length === 0 ? (
        <Card className="p-12 text-center border-dashed border-2">
          <h3 className="text-lg font-medium mb-1">No users found</h3>
          <p className="text-muted-foreground">No users have generated any images yet or your search didn't match anyone.</p>
        </Card>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {data?.stats?.map((stat: any) => (
            <Card key={stat.user._id} className="overflow-hidden hover:shadow-md transition-all flex flex-col border-border/50">
              <CardHeader className="pb-4">
                <div className="flex items-center gap-4">
                  <div className="h-14 w-14 rounded-full bg-primary/10 flex flex-shrink-0 items-center justify-center text-primary font-bold text-xl uppercase overflow-hidden border border-primary/20">
                    {stat.user.avatar ? (
                      <img src={stat.user.avatar} alt="Avatar" className="w-full h-full object-cover" style={{ imageRendering: '-webkit-optimize-contrast' as any }} />
                    ) : (
                      stat.user.name?.charAt(0) || 'U'
                    )}
                  </div>
                  <div className="overflow-hidden">
                    <CardTitle className="text-lg truncate">{stat.user.name}</CardTitle>
                    <p className="text-xs text-muted-foreground truncate" title={stat.user.email}>{stat.user.email}</p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="flex-1 pb-4">
                <div className="bg-muted/30 rounded-lg p-4 border border-border/50 flex flex-col items-center justify-center text-center">
                  <div className="text-3xl font-bold text-primary mb-1">{stat.totalGenerations}</div>
                  <div className="text-sm font-medium text-muted-foreground uppercase tracking-wider">Images Generated</div>
                  {stat.lastGenerationDate && (
                    <div className="text-xs text-muted-foreground mt-3 pt-3 border-t border-border/50 w-full">
                      Last active: {new Date(stat.lastGenerationDate).toLocaleDateString()}
                    </div>
                  )}
                </div>
              </CardContent>
              <CardFooter className="pt-0">
                <Button 
                  className="w-full" 
                  onClick={() => setSelectedUser({ id: stat.user._id, name: stat.user.name })}
                >
                  View all generation report
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}

      {data?.pages > 1 && (
        <div className="flex items-center justify-between mt-8 border-t pt-6">
          <div className="text-sm text-muted-foreground">
            Showing page {page} of {data.pages}
          </div>
          <div className="flex gap-2">
            <Button 
              variant="outline" 
              onClick={() => setPage(p => Math.max(1, p - 1))}
              disabled={page === 1 || isLoading}
            >
              <ChevronLeft className="h-4 w-4 mr-1" /> Previous
            </Button>
            <Button 
              variant="outline" 
              onClick={() => setPage(p => Math.min(data.pages, p + 1))}
              disabled={page >= data?.pages || isLoading}
            >
              Next <ChevronRight className="h-4 w-4 ml-1" />
            </Button>
          </div>
        </div>
      )}

      {/* User Generations Modal */}
      <UserGenerationsModal 
        userId={selectedUser?.id || ''} 
        userName={selectedUser?.name || ''} 
        isOpen={!!selectedUser} 
        onClose={() => setSelectedUser(null)} 
      />
    </div>
  );
}
