import React from "react";
import { Space_Grotesk } from 'next/font/google';
import Navbar from "../_components/Navbar";
import Footer from "../_components/Footer";

const space = Space_Grotesk({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <div className={`w-full bg-[#F3F5F7] min-h-screen py-24 md:py-32 ${space.className}`}>
        <div className="max-w-3xl mx-auto px-4 md:px-8 bg-white p-8 md:p-12 rounded-2xl shadow-[0_4px_24px_rgba(0,0,0,0.02)] border border-gray-100">
          <h1 className="text-[36px] font-bold text-[#14181F] mb-4 tracking-tight">Terms of Service</h1>
          <p className="text-slate-500 mb-10 font-sans">Last updated: March 18, 2026</p>

          <div className="space-y-8 text-[#14181F] text-[15px] leading-relaxed font-sans">
            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">1. Acceptance of Terms</h2>
              <p>By accessing or using MetaGen AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">2. Description of Service</h2>
              <p>MetaGen AI is an AI-powered metadata generation tool designed for stock content contributors. The service allows you to upload images, videos, and vector files to automatically generate titles, descriptions, and keywords optimized for various stock platforms.</p>
            </section>
            
            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">3. Account Registration</h2>
              <ul className="list-disc pl-5 space-y-2 text-slate-600">
                <li>You must provide accurate and complete information when creating an account.</li>
                <li>You are responsible for maintaining the security of your account credentials.</li>
                <li>You must notify us immediately of any unauthorized use of your account.</li>
                <li>Each account is limited to use on the number of devices specified by your plan.</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">4. Credits & Plans</h2>
              <ul className="list-disc pl-5 space-y-2 text-slate-600">
                <li>Free Plan: 150 credits daily, resets every 24 hours.</li>
                <li>Paid Plans: One-time purchases with credits valid for the specified duration.</li>
                <li>Credits are non-transferable and non-refundable.</li>
                <li>Unused credits from paid plans expire after the validity period ends.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">5. Acceptable Use</h2>
              <p className="mb-2">You agree not to:</p>
              <ul className="list-disc pl-5 space-y-2 text-slate-600">
                <li>Use the service for any illegal or unauthorized purpose</li>
                <li>Upload content that infringes on intellectual property rights</li>
                <li>Attempt to reverse engineer, decompile, or hack the service</li>
                <li>Share your account credentials with others</li>
                <li>Use automated scripts or bots to access the service</li>
                <li>Upload malicious files or content</li>
              </ul>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">6. Intellectual Property</h2>
              <p>You retain all rights to your uploaded content and the metadata generated for it. MetaGen AI does not claim ownership of your files or generated metadata. The MetaGen AI platform, including its design, code, and branding, remains our intellectual property.</p>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">7. AI-Generated Content</h2>
              <p>Metadata generated by MetaGen AI is produced using artificial intelligence and may not always be perfectly accurate. You are responsible for reviewing and editing generated metadata before submitting it to stock platforms. MetaGen AI is not liable for any consequences resulting from the use of AI-generated metadata.</p>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">8. Limitation of Liability</h2>
              <p>MetaGen AI is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to lost revenue, rejected submissions, or platform penalties.</p>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">9. Termination</h2>
              <p>We reserve the right to suspend or terminate your account at any time for violation of these terms. You may delete your account at any time through your account settings. Upon termination, your credits and data will be permanently deleted.</p>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">10. Changes to Terms</h2>
              <p>We may modify these Terms of Service at any time. Continued use of MetaGen AI after changes constitutes acceptance of the updated terms. We will notify users of significant changes via email or in-app notification.</p>
            </section>

            <section>
              <h2 className="text-[20px] font-bold mb-3 font-sans">11. Contact</h2>
              <p>For questions about these Terms of Service, please contact us via WhatsApp or through our Discord community.</p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
