"use client";

import { useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useGetAllGenerationsQuery, useGetUserGenerationStatsQuery } from "@/lib/feature/admin/adminApi";
import { ChevronLeft, ChevronRight, Download, Image as ImageIcon, ArrowLeft } from "lucide-react";

export default function UserImageHistoryPage() {
  const params = useParams();
  const router = useRouter();
  const userId = params.id as string;
  
  const [page, setPage] = useState(1);
  const { data, isLoading } = useGetAllGenerationsQuery({ page, limit: 12, userId }, { skip: !userId });

  // Get user details (we can get from the first item or pass as state, but fetching stats is easy)
  const { data: statsData } = useGetUserGenerationStatsQuery({ search: '' });
  const userStat = statsData?.stats?.find((s: any) => s.user._id === userId);
  const userName = userStat?.user?.name || data?.generations?.[0]?.user?.name || 'User';

  const handleDownload = async (imageUrl: string, title: string) => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${title || 'generated-image'}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error("Download failed", error);
      window.open(imageUrl, '_blank');
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col gap-4">
        <Button variant="ghost" className="w-fit pl-0 gap-2 hover:bg-transparent hover:text-primary" onClick={() => router.push('/admin/images')}>
          <ArrowLeft className="h-4 w-4" /> Back to Users
        </Button>
        <div>
          <h2 className="text-3xl font-bold tracking-tight">{userName}'s Generation History</h2>
          <p className="text-muted-foreground">View and download all images generated by this user.</p>
        </div>
      </div>
        
      <div className="mt-4">
        {isLoading ? (
          <div className="flex justify-center items-center py-20">
            <span className="animate-pulse text-muted-foreground text-lg">Loading generations...</span>
          </div>
        ) : data?.generations?.length === 0 ? (
          <Card className="text-center py-16 text-muted-foreground border-dashed border-2">
            <h3 className="text-lg font-medium mb-1">No generation history</h3>
            <p>This user hasn't generated any images yet.</p>
          </Card>
        ) : (
          <>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {data?.generations?.map((item: any) => (
                <Card key={item._id} className="overflow-hidden flex flex-col hover:shadow-md transition-all border-border/50">
                  <div className="aspect-square bg-muted relative group overflow-hidden">
                    {item.imageUrl ? (
                      <img src={item.imageUrl} alt={item.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
                    ) : (
                      <div className="flex items-center justify-center w-full h-full text-muted-foreground">
                        <ImageIcon className="h-10 w-10 opacity-30" />
                      </div>
                    )}
                  </div>
                  <CardContent className="p-4 flex-1 flex flex-col justify-between">
                    <div>
                      <h4 className="font-semibold text-lg truncate" title={item.title || 'Untitled'}>{item.title || 'Untitled'}</h4>
                      <p className="text-xs text-muted-foreground mt-1 line-clamp-2" title={item.description}>{item.description}</p>
                    </div>
                    <div className="flex justify-between items-center mt-4 text-xs font-medium">
                      <span className="bg-primary/10 text-primary px-2.5 py-1 rounded-full capitalize">{item.category}</span>
                      <span className="text-muted-foreground">{new Date(item.createdAt).toLocaleDateString()}</span>
                    </div>
                  </CardContent>
                  <CardFooter className="p-4 pt-0">
                    <Button 
                      variant="default" 
                      className="w-full gap-2 shadow-sm"
                      onClick={() => handleDownload(item.imageUrl, item.title)}
                      disabled={!item.imageUrl}
                    >
                      <Download className="h-4 w-4" /> Download Image
                    </Button>
                  </CardFooter>
                </Card>
              ))}
            </div>
            
            {data?.pages > 1 && (
              <div className="flex items-center justify-between mt-8 pt-6 border-t">
                <div className="text-sm text-muted-foreground font-medium">
                  Page {page} of {data.pages}
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1 || isLoading}>
                    <ChevronLeft className="h-4 w-4 mr-1" /> Previous
                  </Button>
                  <Button variant="outline" onClick={() => setPage(p => Math.min(data.pages, p + 1))} disabled={page >= data?.pages || isLoading}>
                    Next <ChevronRight className="h-4 w-4 ml-1" />
                  </Button>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}