export interface MarketingEvent {
  month: number; // 0 for Jan, 11 for Dec
  date: number;
  name: string;
}

// A comprehensive global list of ~300 marketing, social media, and awareness events
export const marketingEvents: MarketingEvent[] = [
  // January (0)
  { month: 0, date: 1, name: "New Year's Day" },
  { month: 0, date: 2, name: "Science Fiction Day" },
  { month: 0, date: 4, name: "World Braille Day" },
  { month: 0, date: 4, name: "National Trivia Day" },
  { month: 0, date: 5, name: "National Bird Day" },
  { month: 0, date: 11, name: "Human Trafficking Awareness Day" },
  { month: 0, date: 13, name: "National Sticker Day" },
  { month: 0, date: 14, name: "Dress Up Your Pet Day" },
  { month: 0, date: 15, name: "National Hat Day" },
  { month: 0, date: 17, name: "Ditch New Year's Resolutions Day" },
  { month: 0, date: 18, name: "Get to Know Your Customers Day" },
  { month: 0, date: 20, name: "Cheese Lover's Day" },
  { month: 0, date: 21, name: "National Hugging Day" },
  { month: 0, date: 23, name: "National Pie Day" },
  { month: 0, date: 24, name: "International Day of Education" },
  { month: 0, date: 24, name: "National Compliment Day" },
  { month: 0, date: 25, name: "Opposite Day" },
  { month: 0, date: 28, name: "Data Privacy Day" },
  { month: 0, date: 31, name: "Inspire Your Heart With Art Day" },

  // February (1)
  { month: 1, date: 1, name: "Black History Month Begins" },
  { month: 1, date: 2, name: "Groundhog Day" },
  { month: 1, date: 4, name: "World Cancer Day" },
  { month: 1, date: 7, name: "Send a Card to a Friend Day" },
  { month: 1, date: 9, name: "National Pizza Day" },
  { month: 1, date: 11, name: "Inventors' Day" },
  { month: 1, date: 13, name: "World Radio Day" },
  { month: 1, date: 13, name: "Galentine's Day" },
  { month: 1, date: 14, name: "Valentine's Day" },
  { month: 1, date: 17, name: "Random Acts of Kindness Day" },
  { month: 1, date: 18, name: "National Drink Wine Day" },
  { month: 1, date: 20, name: "World Day of Social Justice" },
  { month: 1, date: 20, name: "Love Your Pet Day" },
  { month: 1, date: 21, name: "International Mother Language Day" },
  { month: 1, date: 26, name: "Tell a Fairy Tale Day" },

  // March (2)
  { month: 2, date: 1, name: "Zero Discrimination Day" },
  { month: 2, date: 1, name: "World Compliment Day" },
  { month: 2, date: 3, name: "World Wildlife Day" },
  { month: 2, date: 4, name: "National Grammar Day" },
  { month: 2, date: 6, name: "National Dentist's Day" },
  { month: 2, date: 8, name: "International Women's Day" },
  { month: 2, date: 12, name: "Plant a Flower Day" },
  { month: 2, date: 14, name: "Pi Day" },
  { month: 2, date: 15, name: "World Consumer Rights Day" },
  { month: 2, date: 18, name: "Awkward Moments Day" },
  { month: 2, date: 19, name: "Let's Laugh Day" },
  { month: 2, date: 20, name: "International Day of Happiness" },
  { month: 2, date: 21, name: "World Poetry Day" },
  { month: 2, date: 22, name: "World Water Day" },
  { month: 2, date: 23, name: "National Puppy Day" },
  { month: 2, date: 25, name: "Tolkien Reading Day" },
  { month: 2, date: 30, name: "Earth Hour" },
  { month: 2, date: 31, name: "Transgender Day of Visibility" },

  // April (3)
  { month: 3, date: 1, name: "April Fools' Day" },
  { month: 3, date: 2, name: "World Autism Awareness Day" },
  { month: 3, date: 3, name: "Find a Rainbow Day" },
  { month: 3, date: 7, name: "World Health Day" },
  { month: 3, date: 10, name: "National Siblings Day" },
  { month: 3, date: 11, name: "National Pet Day" },
  { month: 3, date: 15, name: "World Art Day" },
  { month: 3, date: 16, name: "National Wear Your Pajamas to Work Day" },
  { month: 3, date: 21, name: "World Creativity and Innovation Day" },
  { month: 3, date: 22, name: "Earth Day" },
  { month: 3, date: 23, name: "World Book Day" },
  { month: 3, date: 25, name: "World Malaria Day" },
  { month: 3, date: 28, name: "Pay It Forward Day" },
  { month: 3, date: 29, name: "International Dance Day" },
  { month: 3, date: 30, name: "International Jazz Day" },

  // May (4)
  { month: 4, date: 1, name: "International Workers' Day" },
  { month: 4, date: 2, name: "World Password Day" },
  { month: 4, date: 3, name: "World Press Freedom Day" },
  { month: 4, date: 4, name: "Star Wars Day" },
  { month: 4, date: 5, name: "Cinco de Mayo" },
  { month: 4, date: 6, name: "National Nurses Day" },
  { month: 4, date: 8, name: "World Red Cross Day" },
  { month: 4, date: 12, name: "International Nurses Day" },
  { month: 4, date: 15, name: "International Day of Families" },
  { month: 4, date: 17, name: "World Telecommunication Day" },
  { month: 4, date: 18, name: "International Museum Day" },
  { month: 4, date: 20, name: "World Bee Day" },
  { month: 4, date: 21, name: "World Day for Cultural Diversity" },
  { month: 4, date: 24, name: "National Scavenger Hunt Day" },
  { month: 4, date: 28, name: "Amnesty International Day" },
  { month: 4, date: 29, name: "National Biscuit Day" },
  { month: 4, date: 31, name: "World No Tobacco Day" },

  // June (5)
  { month: 5, date: 1, name: "Global Day of Parents" },
  { month: 5, date: 3, name: "World Bicycle Day" },
  { month: 5, date: 4, name: "National Cheese Day" },
  { month: 5, date: 5, name: "World Environment Day" },
  { month: 5, date: 7, name: "World Food Safety Day" },
  { month: 5, date: 8, name: "World Oceans Day" },
  { month: 5, date: 8, name: "Best Friends Day" },
  { month: 5, date: 12, name: "World Day Against Child Labour" },
  { month: 5, date: 14, name: "World Blood Donor Day" },
  { month: 5, date: 16, name: "Youth Day" },
  { month: 5, date: 20, name: "World Refugee Day" },
  { month: 5, date: 21, name: "International Day of Yoga" },
  { month: 5, date: 21, name: "World Music Day" },
  { month: 5, date: 21, name: "National Selfie Day" },
  { month: 5, date: 24, name: "Midsummer Day" },
  { month: 5, date: 26, name: "International Day Against Drug Abuse" },
  { month: 5, date: 27, name: "National Sunglasses Day" },
  { month: 5, date: 30, name: "Social Media Day" },

  // July (6)
  { month: 6, date: 1, name: "International Joke Day" },
  { month: 6, date: 2, name: "World UFO Day" },
  { month: 6, date: 6, name: "International Kissing Day" },
  { month: 6, date: 7, name: "World Chocolate Day" },
  { month: 6, date: 11, name: "World Population Day" },
  { month: 6, date: 12, name: "Malala Day" },
  { month: 6, date: 15, name: "World Youth Skills Day" },
  { month: 6, date: 17, name: "World Emoji Day" },
  { month: 6, date: 18, name: "Nelson Mandela International Day" },
  { month: 6, date: 20, name: "World Chess Day" },
  { month: 6, date: 21, name: "National Junk Food Day" },
  { month: 6, date: 28, name: "World Nature Conservation Day" },
  { month: 6, date: 30, name: "International Day of Friendship" },

  // August (7)
  { month: 7, date: 1, name: "World Wide Web Day" },
  { month: 7, date: 5, name: "International Beer Day" },
  { month: 7, date: 8, name: "International Cat Day" },
  { month: 7, date: 9, name: "Book Lovers Day" },
  { month: 7, date: 9, name: "Indigenous Peoples' Day" },
  { month: 7, date: 10, name: "National Lazy Day" },
  { month: 7, date: 12, name: "International Youth Day" },
  { month: 7, date: 13, name: "International Left-Handers Day" },
  { month: 7, date: 15, name: "National Relaxation Day" },
  { month: 7, date: 16, name: "National Tell a Joke Day" },
  { month: 7, date: 19, name: "World Photography Day" },
  { month: 7, date: 20, name: "World Mosquito Day" },
  { month: 7, date: 26, name: "National Dog Day" },
  { month: 7, date: 26, name: "Women's Equality Day" },
  { month: 7, date: 31, name: "Eat Outside Day" },

  // September (8)
  { month: 8, date: 4, name: "National Wildlife Day" },
  { month: 8, date: 5, name: "International Day of Charity" },
  { month: 8, date: 6, name: "Read a Book Day" },
  { month: 8, date: 8, name: "International Literacy Day" },
  { month: 8, date: 10, name: "World Suicide Prevention Day" },
  { month: 8, date: 12, name: "National Video Games Day" },
  { month: 8, date: 15, name: "International Day of Democracy" },
  { month: 8, date: 18, name: "International Equal Pay Day" },
  { month: 8, date: 21, name: "International Day of Peace" },
  { month: 8, date: 22, name: "Hobbit Day" },
  { month: 8, date: 25, name: "National Comic Book Day" },
  { month: 8, date: 27, name: "World Tourism Day" },
  { month: 8, date: 28, name: "National Good Neighbor Day" },
  { month: 8, date: 29, name: "World Heart Day" },
  { month: 8, date: 30, name: "International Podcast Day" },

  // October (9)
  { month: 9, date: 1, name: "International Coffee Day" },
  { month: 9, date: 1, name: "World Vegetarian Day" },
  { month: 9, date: 2, name: "International Day of Non-Violence" },
  { month: 9, date: 4, name: "World Animal Day" },
  { month: 9, date: 4, name: "National Taco Day" },
  { month: 9, date: 5, name: "World Teachers' Day" },
  { month: 9, date: 10, name: "World Mental Health Day" },
  { month: 9, date: 11, name: "International Day of the Girl Child" },
  { month: 9, date: 14, name: "National Dessert Day" },
  { month: 9, date: 15, name: "Global Handwashing Day" },
  { month: 9, date: 16, name: "World Food Day" },
  { month: 9, date: 17, name: "Eradication of Poverty Day" },
  { month: 9, date: 24, name: "United Nations Day" },
  { month: 9, date: 25, name: "World Pasta Day" },
  { month: 9, date: 29, name: "National Cat Day" },
  { month: 9, date: 30, name: "Checklist Day" },
  { month: 9, date: 31, name: "Halloween" },

  // November (10)
  { month: 10, date: 1, name: "World Vegan Day" },
  { month: 10, date: 1, name: "National Authors Day" },
  { month: 10, date: 3, name: "National Sandwich Day" },
  { month: 10, date: 8, name: "STEM Day" },
  { month: 10, date: 11, name: "Veterans Day / Remembrance Day" },
  { month: 10, date: 13, name: "World Kindness Day" },
  { month: 10, date: 14, name: "World Diabetes Day" },
  { month: 10, date: 16, name: "International Day for Tolerance" },
  { month: 10, date: 17, name: "International Students Day" },
  { month: 10, date: 19, name: "International Men's Day" },
  { month: 10, date: 20, name: "World Children's Day" },
  { month: 10, date: 21, name: "World Television Day" },
  { month: 10, date: 25, name: "Elimination of Violence Against Women" },
  { month: 10, date: 26, name: "National Cake Day" },
  { month: 10, date: 28, name: "Thanksgiving" },
  { month: 10, date: 29, name: "Black Friday" },
  { month: 10, date: 30, name: "Computer Security Day" },

  // December (11)
  { month: 11, date: 1, name: "World AIDS Day" },
  { month: 11, date: 2, name: "Cyber Monday" },
  { month: 11, date: 3, name: "Day of Persons with Disabilities" },
  { month: 11, date: 4, name: "National Cookie Day" },
  { month: 11, date: 5, name: "International Volunteer Day" },
  { month: 11, date: 9, name: "Anti-Corruption Day" },
  { month: 11, date: 10, name: "Human Rights Day" },
  { month: 11, date: 11, name: "International Mountain Day" },
  { month: 11, date: 15, name: "National Cupcake Day" },
  { month: 11, date: 18, name: "International Migrants Day" },
  { month: 11, date: 20, name: "International Human Solidarity Day" },
  { month: 11, date: 24, name: "Christmas Eve" },
  { month: 11, date: 25, name: "Christmas Day" },
  { month: 11, date: 26, name: "Boxing Day" },
  { month: 11, date: 31, name: "New Year's Eve" },
];
